module.exports = {
User: require('./usersModel'),
Role: require('./role.model'),
UserRole: require('./userRole.model'),
Permission: require('./permission.model'),
RolePermission: require('./rolePermission.model'),
AuthProvider: require('./authProvider.model'),
Center: require('./center.model'),
CenterMember: require('./centerMember.model'),
Group: require('./group.model'),
GroupMember: require('./groupMember.model'),
Board: require('./board.model'),
BoardMember: require('./boardMember.model'),
BoardGroup: require('./boardGroup.model'),
Column: require('./column.model'),
Swimlane: require('./swimlane.model'),
Task: require('./task.model'),
Tag: require('./tag.model'),
TaskTag: require('./taskTag.model'),
Comment: require('./comment.model'),
ActivityLog: require('./activityLog.model'),
Template: require('./template.model'),
TemplateColumn: require('./templateColumn.model'),
TemplateSwimlane: require('./templateSwimlane.model'),
ImportJob: require('./importJob.model'),
UserPoint: require('./userPoint.model'),
Notification: require('./notification.model'),
};